hepsi: derle bagla calistir

derle:
	g++ -I ./include/ -o ./lib/node.o -c ./src/node.cpp
	g++ -I ./include/ -o ./lib/linkedlist.o -c ./src/linkedlist.cpp
	g++ -I ./include/ -o ./lib/odevv.o -c ./src/odevv.cpp	
bagla:
	g++ ./lib/node.o  ./lib/linkedlist.o ./lib/odevv.o -o ./bin/program

calistir:
	./bin/program
